name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      bool:
        description: 'Bool'
        required: false
        type: boolean

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        env:
          LOG_LEVEL: ${{ inputs.logLevel }}
          BOOL: ${{ inputs.bool }}
        run: |
          echo "Log level: $LOG_LEVEL"
          echo "Bool: $BOOL"
