name: Scheduled workflow

on:
  schedule:
    - cron: '0 0 1 1 *' # At 00:00 on day-of-month 1 in January

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi
        run: echo "Hi from scheduled workflow"
