name: Workflow call consumer

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow_call_consumer:
    uses: ./.github/workflows/workflow_call_provider.yml
    with:
      x: "consumer_value_x"
